name: RELEASE

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release-please
        with:
          token: ${{ secrets.GH_PAT }}
          release-type: node

      - name: Checkout
        if: ${{ steps.release-please.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Setup Node
        if: ${{ steps.release-please.outputs.release_created }}
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org
          node-version-file: .nvmrc
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Build
        if: ${{ steps.release-please.outputs.release_created }}
        run: |
          yarn
          yarn build
        env:
          CI: true
  
      - name: Publish to npm registry
        if: ${{ steps.release-please.outputs.release_created }}
        run: yarn publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}